"""add another tables

Revision ID: ecf1076c56aa
Revises: 9e3a68c98077
Create Date: 2025-08-15 21:54:19.507755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf1076c56aa'
down_revision: Union[str, Sequence[str], None] = '9e3a68c98077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('total_price_cents', sa.Integer(), nullable=False))
    op.alter_column('orders', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'bottle_count')
    op.drop_column('orders', 'flavor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('flavor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('bottle_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('orders', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('orders', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('orders', 'total_price_cents')
    op.drop_table('order_items')
    op.drop_table('products')
    # ### end Alembic commands ###
